services:
  - type: web
    name: your-backend-service
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    plan: free
    autoDeploy: true